/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.trabajogrupal2;

import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author Santiago Jimenez Escobar
 *  Kevin Andres Zapata Nuñez
 */
public class VentanaTrabajo extends javax.swing.JFrame {

    ArrayList arrayClientes = new ArrayList();
    ArrayList arrayPizza = new ArrayList();
    ArrayList arrayTamaño = new ArrayList();
    ArrayList arrayBebidas = new ArrayList();
    ArrayList arrayDomicilio = new ArrayList();
    ArrayList arrayDireccion = new ArrayList();
    ArrayList arrayValores = new ArrayList();
    
    
    
    DefaultListModel modeloClientes = new DefaultListModel();
    DefaultListModel modeloValores = new DefaultListModel();
    
    private double valorTotal=0;
    private double valorPizza=0;
    private double valorTamaño=0;
    private double valorANinguno=0;
    private double valorQueso=0;
    private double valorChampiñones=0;
    private double valorBordeQueso=0;
    private double valorPiña=0;
    private double valorMaiz=0;
    private double valorTocino=0;
    private double valorBebida=0;
    private double valorDomicilio=0;
    private double sumaVentas=0;
    private int cantidadPedidos=0;
    private int contarSencilla=0;
    private int contarCuatroCarnes = 0;
    private int contarHawaina = 0;
    private int contarHolandesa = 0;
    private int contarLaEscoses = 0;
    private int contarPolloChampiñones = 0;
    private int contarRanchera = 0;
    private int contarVegetariana = 0;
    private int contarPersonal = 0;
    private int contarFamiliar = 0;
    private int contarGrande = 0;
    private int contarExtraGrande = 0;

    
    
    public VentanaTrabajo() {
        initComponents();
        setTitle("Ventana Trabajo");
        
        btnG.add(rbNo);
        btnG.add(rbSi);
        btnGPizzas.add(rbSencilla);
        btnGPizzas.add(rbCuatroCarnes);
        btnGPizzas.add(rbHawaina);
        btnGPizzas.add(rbHolandesa);
        btnGPizzas.add(rbLaEscoses);
        btnGPizzas.add(rbPolloChampiñones);
        btnGPizzas.add(rbRanchera);
        btnGPizzas.add(rbVegetariana);
        txtValorDomicilio.setVisible(false);
        lbValorDomicilio.setVisible(false);
        jlClientes.setModel(modeloClientes);
        jlvalores.setModel(modeloValores);
    }
    
    
    public void modificarBienvenida2(String usuario) {
        lbUsuario.setText("Usuario conectado: "+usuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnG = new javax.swing.ButtonGroup();
        btnGPizzas = new javax.swing.ButtonGroup();
        jpPrincipal = new javax.swing.JPanel();
        lbUsuario = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        jpNustrasPizzas = new javax.swing.JPanel();
        rbSencilla = new javax.swing.JRadioButton();
        rbHawaina = new javax.swing.JRadioButton();
        rbRanchera = new javax.swing.JRadioButton();
        rbHolandesa = new javax.swing.JRadioButton();
        rbLaEscoses = new javax.swing.JRadioButton();
        rbPolloChampiñones = new javax.swing.JRadioButton();
        rbVegetariana = new javax.swing.JRadioButton();
        rbCuatroCarnes = new javax.swing.JRadioButton();
        jpTamaño = new javax.swing.JPanel();
        ComboBoxTamaño = new javax.swing.JComboBox<>();
        jpAdiciones = new javax.swing.JPanel();
        cbQuesoMozarela = new javax.swing.JCheckBox();
        cbChampiñones = new javax.swing.JCheckBox();
        cbBordeDeQueso = new javax.swing.JCheckBox();
        cbPiña = new javax.swing.JCheckBox();
        cbMaiz = new javax.swing.JCheckBox();
        cbTocino = new javax.swing.JCheckBox();
        cbANinguna = new javax.swing.JCheckBox();
        jpBebidas = new javax.swing.JPanel();
        ComboBoxBebidas = new javax.swing.JComboBox<>();
        jpDatosDelCliente = new javax.swing.JPanel();
        lbNombre = new javax.swing.JLabel();
        lbTelefono = new javax.swing.JLabel();
        lbDireccion = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        jpDomicilio = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        rbSi = new javax.swing.JRadioButton();
        rbNo = new javax.swing.JRadioButton();
        lbValorDomicilio = new javax.swing.JLabel();
        txtValorDomicilio = new javax.swing.JTextField();
        lbTotal = new javax.swing.JLabel();
        txtValorTotal = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlClientes = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlvalores = new javax.swing.JList<>();
        btnConsultarPedidos = new javax.swing.JButton();
        btnCambioUsuario = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();
        jPanel33 = new javax.swing.JPanel();
        jPanel34 = new javax.swing.JPanel();
        jPanel35 = new javax.swing.JPanel();
        jPanel36 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpPrincipal.setBackground(new java.awt.Color(238, 191, 121));

        btnSalir.setBackground(new java.awt.Color(249, 159, 36));
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnAtras.setBackground(new java.awt.Color(249, 159, 36));
        btnAtras.setText("ATRAS");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        jpNustrasPizzas.setBackground(new java.awt.Color(244, 220, 174));
        jpNustrasPizzas.setBorder(javax.swing.BorderFactory.createTitledBorder("Nuestras Pizzas"));

        rbSencilla.setText("Sencilla");

        rbHawaina.setText("Hawaina");

        rbRanchera.setText("Ranchera");

        rbHolandesa.setText("Holandesa");

        rbLaEscoses.setText("La Escoses");

        rbPolloChampiñones.setText("Pollo Champiñones");

        rbVegetariana.setText("Vegetariana");

        rbCuatroCarnes.setText("Cuatro Carnes");

        javax.swing.GroupLayout jpNustrasPizzasLayout = new javax.swing.GroupLayout(jpNustrasPizzas);
        jpNustrasPizzas.setLayout(jpNustrasPizzasLayout);
        jpNustrasPizzasLayout.setHorizontalGroup(
            jpNustrasPizzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNustrasPizzasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpNustrasPizzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpNustrasPizzasLayout.createSequentialGroup()
                        .addGroup(jpNustrasPizzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbLaEscoses)
                            .addComponent(rbPolloChampiñones))
                        .addContainerGap(84, Short.MAX_VALUE))
                    .addGroup(jpNustrasPizzasLayout.createSequentialGroup()
                        .addGroup(jpNustrasPizzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbSencilla)
                            .addComponent(rbHawaina)
                            .addComponent(rbRanchera)
                            .addComponent(rbHolandesa)
                            .addComponent(rbVegetariana)
                            .addComponent(rbCuatroCarnes))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jpNustrasPizzasLayout.setVerticalGroup(
            jpNustrasPizzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNustrasPizzasLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(rbSencilla)
                .addGap(18, 18, 18)
                .addComponent(rbHawaina)
                .addGap(18, 18, 18)
                .addComponent(rbRanchera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbHolandesa)
                .addGap(18, 18, 18)
                .addComponent(rbLaEscoses)
                .addGap(18, 18, 18)
                .addComponent(rbPolloChampiñones)
                .addGap(18, 18, 18)
                .addComponent(rbVegetariana)
                .addGap(18, 18, 18)
                .addComponent(rbCuatroCarnes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpTamaño.setBackground(new java.awt.Color(244, 220, 174));
        jpTamaño.setBorder(javax.swing.BorderFactory.createTitledBorder("Tamaño"));

        ComboBoxTamaño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Personal (4 pociones)", "Familiar (6 porciones)", "Grande (8 porciones)", "Extra Grande (12 porciones)" }));

        javax.swing.GroupLayout jpTamañoLayout = new javax.swing.GroupLayout(jpTamaño);
        jpTamaño.setLayout(jpTamañoLayout);
        jpTamañoLayout.setHorizontalGroup(
            jpTamañoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTamañoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ComboBoxTamaño, 0, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpTamañoLayout.setVerticalGroup(
            jpTamañoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTamañoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ComboBoxTamaño, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpAdiciones.setBackground(new java.awt.Color(244, 220, 174));
        jpAdiciones.setBorder(javax.swing.BorderFactory.createTitledBorder("Adiciones"));

        cbQuesoMozarela.setText("Queso Mozarela");

        cbChampiñones.setText("Champiñones");
        cbChampiñones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbChampiñonesActionPerformed(evt);
            }
        });

        cbBordeDeQueso.setText("Borde de Queso");

        cbPiña.setText("Piña");
        cbPiña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPiñaActionPerformed(evt);
            }
        });

        cbMaiz.setText("Maiz");

        cbTocino.setText("Tocino");

        cbANinguna.setText("Ninguna");

        javax.swing.GroupLayout jpAdicionesLayout = new javax.swing.GroupLayout(jpAdiciones);
        jpAdiciones.setLayout(jpAdicionesLayout);
        jpAdicionesLayout.setHorizontalGroup(
            jpAdicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAdicionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpAdicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbQuesoMozarela)
                    .addComponent(cbChampiñones)
                    .addComponent(cbBordeDeQueso)
                    .addComponent(cbPiña)
                    .addComponent(cbMaiz)
                    .addComponent(cbTocino)
                    .addComponent(cbANinguna))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpAdicionesLayout.setVerticalGroup(
            jpAdicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAdicionesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbANinguna)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbQuesoMozarela)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbChampiñones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbBordeDeQueso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbPiña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbMaiz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbTocino)
                .addContainerGap())
        );

        jpBebidas.setBackground(new java.awt.Color(244, 220, 174));
        jpBebidas.setBorder(javax.swing.BorderFactory.createTitledBorder("Bebidas"));

        ComboBoxBebidas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguna", "Gaseosa", "Jugo Natural", "Tee", "Cerveza", "Limonada", "Coca-Cola" }));

        javax.swing.GroupLayout jpBebidasLayout = new javax.swing.GroupLayout(jpBebidas);
        jpBebidas.setLayout(jpBebidasLayout);
        jpBebidasLayout.setHorizontalGroup(
            jpBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBebidasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ComboBoxBebidas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpBebidasLayout.setVerticalGroup(
            jpBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBebidasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ComboBoxBebidas, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpDatosDelCliente.setBackground(new java.awt.Color(244, 220, 174));
        jpDatosDelCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Cliente"));

        lbNombre.setText("Nombre");

        lbTelefono.setText("Telefono");

        lbDireccion.setText("Direccion");

        javax.swing.GroupLayout jpDatosDelClienteLayout = new javax.swing.GroupLayout(jpDatosDelCliente);
        jpDatosDelCliente.setLayout(jpDatosDelClienteLayout);
        jpDatosDelClienteLayout.setHorizontalGroup(
            jpDatosDelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDatosDelClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDatosDelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDatosDelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDireccion))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpDatosDelClienteLayout.setVerticalGroup(
            jpDatosDelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDatosDelClienteLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jpDatosDelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jpDatosDelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jpDatosDelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        jpDomicilio.setBackground(new java.awt.Color(244, 220, 174));
        jpDomicilio.setBorder(javax.swing.BorderFactory.createTitledBorder("Domicilio"));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Incluir Domicilio");

        rbSi.setText("SI");
        rbSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSiActionPerformed(evt);
            }
        });

        rbNo.setText("NO");
        rbNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNoActionPerformed(evt);
            }
        });

        lbValorDomicilio.setText("VALOR");

        javax.swing.GroupLayout jpDomicilioLayout = new javax.swing.GroupLayout(jpDomicilio);
        jpDomicilio.setLayout(jpDomicilioLayout);
        jpDomicilioLayout.setHorizontalGroup(
            jpDomicilioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDomicilioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDomicilioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpDomicilioLayout.createSequentialGroup()
                        .addGroup(jpDomicilioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbValorDomicilio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jpDomicilioLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(rbSi)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpDomicilioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpDomicilioLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(rbNo))
                            .addComponent(txtValorDomicilio))))
                .addContainerGap())
        );
        jpDomicilioLayout.setVerticalGroup(
            jpDomicilioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDomicilioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDomicilioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbSi)
                    .addComponent(rbNo))
                .addGap(18, 18, 18)
                .addGroup(jpDomicilioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbValorDomicilio)
                    .addComponent(txtValorDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        lbTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTotal.setText("TOTAL");

        btnCalcular.setBackground(new java.awt.Color(249, 159, 36));
        btnCalcular.setText("CALCULAR");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnNuevo.setBackground(new java.awt.Color(249, 159, 36));
        btnNuevo.setText("NUEVO");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnListar.setBackground(new java.awt.Color(249, 159, 36));
        btnListar.setText("LISTAR");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        jlClientes.setBackground(new java.awt.Color(244, 220, 174));
        jlClientes.setBorder(javax.swing.BorderFactory.createTitledBorder("Clientes"));
        jScrollPane1.setViewportView(jlClientes);

        jlvalores.setBackground(new java.awt.Color(244, 220, 174));
        jlvalores.setBorder(javax.swing.BorderFactory.createTitledBorder("Valores"));
        jScrollPane2.setViewportView(jlvalores);

        btnConsultarPedidos.setBackground(new java.awt.Color(249, 159, 36));
        btnConsultarPedidos.setText("CONSULTAR PEDIDOS");
        btnConsultarPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarPedidosActionPerformed(evt);
            }
        });

        btnCambioUsuario.setBackground(new java.awt.Color(249, 159, 36));
        btnCambioUsuario.setText("CAMBIO USUARIO");
        btnCambioUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambioUsuarioActionPerformed(evt);
            }
        });

        jPanel14.setBackground(new java.awt.Color(160, 16, 5));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(47, 75, 14));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(160, 16, 5));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(192, 192, 192));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel8.setBackground(new java.awt.Color(47, 75, 14));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel10.setBackground(new java.awt.Color(192, 192, 192));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel11.setBackground(new java.awt.Color(47, 75, 14));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel13.setBackground(new java.awt.Color(160, 16, 5));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("El Parmessano");

        jPanel26.setBackground(new java.awt.Color(160, 16, 5));

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel27.setBackground(new java.awt.Color(47, 75, 14));

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel28.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel29.setBackground(new java.awt.Color(160, 16, 5));

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel30.setBackground(new java.awt.Color(192, 192, 192));

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel31.setBackground(new java.awt.Color(47, 75, 14));

        javax.swing.GroupLayout jPanel31Layout = new javax.swing.GroupLayout(jPanel31);
        jPanel31.setLayout(jPanel31Layout);
        jPanel31Layout.setHorizontalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanel31Layout.setVerticalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel32.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel32Layout = new javax.swing.GroupLayout(jPanel32);
        jPanel32.setLayout(jPanel32Layout);
        jPanel32Layout.setHorizontalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanel32Layout.setVerticalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel33.setBackground(new java.awt.Color(192, 192, 192));

        javax.swing.GroupLayout jPanel33Layout = new javax.swing.GroupLayout(jPanel33);
        jPanel33.setLayout(jPanel33Layout);
        jPanel33Layout.setHorizontalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanel33Layout.setVerticalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel34.setBackground(new java.awt.Color(47, 75, 14));

        javax.swing.GroupLayout jPanel34Layout = new javax.swing.GroupLayout(jPanel34);
        jPanel34.setLayout(jPanel34Layout);
        jPanel34Layout.setHorizontalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanel34Layout.setVerticalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel35.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel35Layout = new javax.swing.GroupLayout(jPanel35);
        jPanel35.setLayout(jPanel35Layout);
        jPanel35Layout.setHorizontalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanel35Layout.setVerticalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel36.setBackground(new java.awt.Color(160, 16, 5));

        javax.swing.GroupLayout jPanel36Layout = new javax.swing.GroupLayout(jPanel36);
        jPanel36.setLayout(jPanel36Layout);
        jPanel36Layout.setHorizontalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanel36Layout.setVerticalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpPrincipalLayout = new javax.swing.GroupLayout(jpPrincipal);
        jpPrincipal.setLayout(jpPrincipalLayout);
        jpPrincipalLayout.setHorizontalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPrincipalLayout.createSequentialGroup()
                        .addComponent(jPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpPrincipalLayout.createSequentialGroup()
                        .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jpNustrasPizzas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpPrincipalLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(374, 374, 374))
                            .addGroup(jpPrincipalLayout.createSequentialGroup()
                                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpPrincipalLayout.createSequentialGroup()
                                        .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jpAdiciones, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jpTamaño, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jpBebidas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jpDatosDelCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jpDomicilio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jpPrincipalLayout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(lbTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(jpPrincipalLayout.createSequentialGroup()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                                    .addGroup(jpPrincipalLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btnAtras)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnSalir)))
                                .addGap(19, 19, 19))))
                    .addGroup(jpPrincipalLayout.createSequentialGroup()
                        .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpPrincipalLayout.createSequentialGroup()
                                .addComponent(btnCambioUsuario)
                                .addGap(204, 204, 204)
                                .addComponent(btnCalcular)
                                .addGap(42, 42, 42)
                                .addComponent(btnNuevo)
                                .addGap(40, 40, 40)
                                .addComponent(btnListar)
                                .addGap(28, 28, 28)
                                .addComponent(btnConsultarPedidos)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jpPrincipalLayout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jpPrincipalLayout.setVerticalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPrincipalLayout.createSequentialGroup()
                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpPrincipalLayout.createSequentialGroup()
                        .addComponent(jpTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpAdiciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jpNustrasPizzas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpPrincipalLayout.createSequentialGroup()
                        .addComponent(jpDatosDelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpDomicilio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpPrincipalLayout.createSequentialGroup()
                        .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTotal))))
                .addGap(18, 18, 18)
                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPrincipalLayout.createSequentialGroup()
                        .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCalcular)
                            .addComponent(btnNuevo)
                            .addComponent(btnListar)
                            .addComponent(btnConsultarPedidos)
                            .addComponent(btnCambioUsuario))
                        .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSalir)
                            .addComponent(btnAtras))
                        .addGap(0, 5, Short.MAX_VALUE))
                    .addGroup(jpPrincipalLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        Autenticacion login = new Autenticacion();
        login.setVisible(true);
        login.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void cbPiñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPiñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPiñaActionPerformed

    private void cbChampiñonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbChampiñonesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbChampiñonesActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        rbSencilla.setSelected(true);
        rbHawaina.setSelected(false);
        rbRanchera.setSelected(false);
        rbHolandesa.setSelected(false);
        rbLaEscoses.setSelected(false);
        rbPolloChampiñones.setSelected(false);
        rbVegetariana.setSelected(false);
        rbCuatroCarnes.setSelected(false);
        ComboBoxTamaño.setSelectedIndex(0);
        cbANinguna.setSelected(true);
        cbQuesoMozarela.setSelected(false);
        cbChampiñones.setSelected(false);
        cbBordeDeQueso.setSelected(false);
        cbPiña.setSelected(false);
        cbMaiz.setSelected(false);
        cbTocino.setSelected(false);
        ComboBoxBebidas.setSelectedIndex(0);
        txtNombre.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        rbNo.setSelected(true);
        rbSi.setSelected(false);
        txtValorDomicilio.setText("");
        txtValorTotal.setText("");
        this.txtNombre.requestFocus();
        txtValorDomicilio.setEditable(false);
        txtValorDomicilio.setEnabled(false);
        txtValorDomicilio.setVisible(false);
        lbValorDomicilio.setVisible(false);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void rbNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNoActionPerformed
        txtValorDomicilio.setText("");
        txtValorDomicilio.setEditable(false);
        txtValorDomicilio.setEnabled(false);
        txtValorDomicilio.setVisible(false);
        lbValorDomicilio.setVisible(false);
    }//GEN-LAST:event_rbNoActionPerformed

    private void rbSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSiActionPerformed
        txtValorDomicilio.setText("");
        txtValorDomicilio.setEditable(true);
        txtValorDomicilio.setEnabled(true);
        txtValorDomicilio.setVisible(true);
        lbValorDomicilio.setVisible(true);
    }//GEN-LAST:event_rbSiActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        int i;
        sumaVentas= sumaVentas + valorTotal;
        cantidadPedidos = cantidadPedidos+1;
        modeloClientes.removeAllElements();
        modeloValores.removeAllElements();
        
        if (rbSencilla.isSelected()) {
            contarSencilla = contarSencilla+1;
        } else if (rbCuatroCarnes.isSelected()) {
            contarCuatroCarnes = contarCuatroCarnes+1;
        } else if (rbHawaina.isSelected()) {
            contarHawaina = contarHawaina+1;
        } else if (rbHolandesa.isSelected()) {
            contarHolandesa = contarHolandesa+1;
        } else if (rbLaEscoses.isSelected()) {
            contarLaEscoses = contarLaEscoses+1;
        } else if (rbPolloChampiñones.isSelected()) {
            contarPolloChampiñones = contarPolloChampiñones+1;
        } else if (rbRanchera.isSelected()) {
            contarRanchera = contarRanchera+1;
        } else if (rbVegetariana.isSelected()) {
            contarVegetariana = contarVegetariana+1;
        }
        
        if (ComboBoxTamaño.getSelectedIndex() == 0) {
            contarPersonal = contarPersonal+1;
        } else if (ComboBoxTamaño.getSelectedIndex() == 1) {
            contarFamiliar = contarFamiliar+1;
        } else if (ComboBoxTamaño.getSelectedIndex() == 2) {
            contarGrande = contarGrande+1;
        } else if (ComboBoxTamaño.getSelectedIndex() == 3) {
            contarExtraGrande = contarExtraGrande+1;
        }

        for (i = 0; i < arrayClientes.size(); i++) {
            modeloClientes.addElement(arrayClientes.get(i));
            modeloValores.addElement(arrayValores.get(i));
        }
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        valorTotal = 0;
        valorPizza = 0;
        valorTamaño = 0;
        valorANinguno = 0;
        valorQueso = 0;
        valorChampiñones = 0;
        valorBordeQueso = 0;
        valorPiña = 0;
        valorMaiz = 0;
        valorTocino = 0;
        valorBebida = 0;
        valorDomicilio=0;
        String nombreCliente="", direccionCliente="", telefonoCliente="";
        String valorCliente="0", pizza="", tamaño="", bebida="", domicilio="";
        
        if (rbSencilla.isSelected()) {
            valorPizza=8000;
            pizza="Sencilla";
        } else if (rbCuatroCarnes.isSelected()) {
            valorPizza=22000;
            pizza="Cuatro Carnes";
        } else if (rbHawaina.isSelected()) {
            valorPizza=15000;
            pizza="Hawaina";
        } else if (rbHolandesa.isSelected()) {
            valorPizza=32000;
            pizza="Holandesa";
        } else if (rbLaEscoses.isSelected()) {
            valorPizza=13500;
            pizza="La Escoses";
        } else if (rbPolloChampiñones.isSelected()) {
            valorPizza=20000;
            pizza="Pollo Champiñones";
        } else if (rbRanchera.isSelected()) {
            valorPizza=18700;
            pizza="Ranchera";
        } else if (rbVegetariana.isSelected()) {
            valorPizza=15200;
            pizza="Vegetariana";
        }
        
        if (ComboBoxTamaño.getSelectedIndex() == 0) {
            valorTamaño=2000;
            tamaño="Personal";
        } else if (ComboBoxTamaño.getSelectedIndex() == 1) {
            valorTamaño=4500;
            tamaño="Familiar";
        } else if (ComboBoxTamaño.getSelectedIndex() == 2) {
            valorTamaño=7000;
            tamaño="Grande";
        } else if (ComboBoxTamaño.getSelectedIndex() == 3) {
            valorTamaño=10000;
            tamaño="Extra Grande";
        }
        
        if (cbANinguna.isSelected()) {
            valorANinguno=0;
        }
        if (cbBordeDeQueso.isSelected()) {
            valorBordeQueso=2500;
        }
        if (cbChampiñones.isSelected()) {
            valorChampiñones=3000;
        }
        if (cbMaiz.isSelected()) {
            valorMaiz=1700;
        }
        if (cbPiña.isSelected()) {
            valorPiña=2400;
        }
        if (cbQuesoMozarela.isSelected()) {
            valorQueso=3200;
        }
        if (cbTocino.isSelected()) {
            valorTocino=3300;
        }
        
        
        if (ComboBoxBebidas.getSelectedIndex() == 0) {
            valorBebida=0;
            bebida="Ninguna";
        } else if (ComboBoxBebidas.getSelectedIndex() == 1) {
            valorBebida=1500;
            bebida="Gaseosa";
        } else if (ComboBoxBebidas.getSelectedIndex() == 2) {
            valorBebida=2500;
            bebida="Jugo Natural";
        } else if (ComboBoxBebidas.getSelectedIndex() == 3) {
            valorBebida=1200;
            bebida="Tee";
        } else if (ComboBoxBebidas.getSelectedIndex() == 4) {
            valorBebida=3200;
            bebida="Cerveza";
        } else if (ComboBoxBebidas.getSelectedIndex() == 5) {
            valorBebida=2400;
            bebida="Limonada";
        } else if (ComboBoxBebidas.getSelectedIndex() == 6) {
            valorBebida=3000;
            bebida="Coca-Cola";
        }
        
        if(rbSi.isSelected()) {
            valorDomicilio = Double.valueOf(txtValorDomicilio.getText());
            domicilio="Si";
        } else {
            domicilio="No";
        }
        
        valorTotal = valorPizza + valorTamaño + valorANinguno + valorBordeQueso + valorChampiñones +
                valorMaiz + valorPiña + valorQueso + valorTocino + valorBebida + valorDomicilio;
        
        txtValorTotal.setText(Double.toString(valorTotal));
        nombreCliente = txtNombre.getText();
        direccionCliente = txtDireccion.getText();
        telefonoCliente = txtTelefono.getText();
        valorCliente = txtValorTotal.getText();
        
        arrayClientes.add(nombreCliente);
        arrayPizza.add(pizza);
        arrayTamaño.add(tamaño);
        arrayBebidas.add(bebida);
        arrayDomicilio.add(domicilio);
        arrayDireccion.add(direccionCliente);
        arrayValores.add(valorCliente);
        
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnConsultarPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarPedidosActionPerformed
        InformacionPedidos ped = new InformacionPedidos();
        ped.setVisible(true);
        ped.setLocationRelativeTo(null);
        ped.setArrayNombres(arrayClientes);
        ped.setArrayPizza(arrayPizza);
        ped.setArrayTamaño(arrayTamaño);
        ped.setArrayBebidas(arrayBebidas);
        ped.setArrayDomicilio(arrayDomicilio);
        ped.setArrayDireccion(arrayDireccion);
        ped.setArrayValorTotal(arrayValores);
        ped.limpiarModelosPedidos();
    }//GEN-LAST:event_btnConsultarPedidosActionPerformed

    private void btnCambioUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambioUsuarioActionPerformed
        Autenticacion login = new Autenticacion();
        login.setVisible(true);
        login.setLocationRelativeTo(null);
        login.GurdarInfoAdmin(this.sumaVentas, this.cantidadPedidos, this.contarSencilla, this.contarCuatroCarnes, 
                this.contarHawaina, this.contarHolandesa, this.contarLaEscoses, this.contarPolloChampiñones,
                this.contarRanchera, this.contarVegetariana, this.contarPersonal, this.contarFamiliar, this.contarGrande,
                this.contarExtraGrande);
    }//GEN-LAST:event_btnCambioUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxBebidas;
    private javax.swing.JComboBox<String> ComboBoxTamaño;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnCambioUsuario;
    private javax.swing.JButton btnConsultarPedidos;
    private javax.swing.ButtonGroup btnG;
    private javax.swing.ButtonGroup btnGPizzas;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JCheckBox cbANinguna;
    private javax.swing.JCheckBox cbBordeDeQueso;
    private javax.swing.JCheckBox cbChampiñones;
    private javax.swing.JCheckBox cbMaiz;
    private javax.swing.JCheckBox cbPiña;
    private javax.swing.JCheckBox cbQuesoMozarela;
    private javax.swing.JCheckBox cbTocino;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> jlClientes;
    private javax.swing.JList<String> jlvalores;
    private javax.swing.JPanel jpAdiciones;
    private javax.swing.JPanel jpBebidas;
    private javax.swing.JPanel jpDatosDelCliente;
    private javax.swing.JPanel jpDomicilio;
    private javax.swing.JPanel jpNustrasPizzas;
    private javax.swing.JPanel jpPrincipal;
    private javax.swing.JPanel jpTamaño;
    private javax.swing.JLabel lbDireccion;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbTelefono;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JLabel lbValorDomicilio;
    private javax.swing.JRadioButton rbCuatroCarnes;
    private javax.swing.JRadioButton rbHawaina;
    private javax.swing.JRadioButton rbHolandesa;
    private javax.swing.JRadioButton rbLaEscoses;
    private javax.swing.JRadioButton rbNo;
    private javax.swing.JRadioButton rbPolloChampiñones;
    private javax.swing.JRadioButton rbRanchera;
    private javax.swing.JRadioButton rbSencilla;
    private javax.swing.JRadioButton rbSi;
    private javax.swing.JRadioButton rbVegetariana;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtValorDomicilio;
    private javax.swing.JTextField txtValorTotal;
    // End of variables declaration//GEN-END:variables
}
